#!/usr/bin/env python3
"""Regenerate npc_group_fixture.txt from the authoritative Python implementation.

The C# client has its own port of normalize_npc_group (mudsharp/Combat/NpcGroups.cs) because the
live HUD needs to bucket fights the same way the offline sqlite pipeline does. Two copies of a rule
drift; NpcGroupsTests reads the fixture this writes and asserts the C# output matches it, so a
change on either side fails the build instead of silently splitting history into two buckets.

Run after touching normalize_npc_group or IRREGULAR_GROUPS:

    python tools/combat/gen_npc_group_fixture.py
"""

from pathlib import Path

from reduce_combat import normalize_npc_group

# Chosen to cover every branch of the rule, not to be a realistic bestiary: instance-number
# stripping, each irregular, the -es / -ies / -s suffix paths, vowel-vs-consonant before a trailing
# y, multi-token and hyphenated names, case folding, and surrounding whitespace.
NAMES = [
    "rat0", "rat", "dwarf1", "dwarf", "mouse0", "thief3", "wolf2", "goat0", "ram1", "zombie0",
    "vampire", "starfish0", "fox1", "harpy0", "donkey0", "ogre2", "box0", "witch1", "bush0",
    "giant cave bat", "black-cat", "snake0", "axe-man", "GOAT0", "  rat1  ", "lynx0", "elf5",
    "fish0",
]

HEADER = """\
# GENERATED by tools/combat/gen_npc_group_fixture.py -- do not hand-edit.
#
# npc instance name | normalized group, per reduce_combat.normalize_npc_group.
# Consumed by mudsharp.Tests NpcGroupsTests to pin the C# port (mudsharp/Combat/NpcGroups.cs) to
# this exact behaviour.
#
# NB: some outputs are not correct English -- "elf5" -> "elfs", "axe-man" -> "mans". That is what
# the rule does today, and AGREEMENT between the two implementations is what this fixture protects,
# not linguistic quality. If the rule is improved, regenerate this file; do not "fix" one side only.
"""


def main() -> None:
    lines = [HEADER]
    for name in NAMES:
        lines.append(f"{name}|{normalize_npc_group(name)}")
    output = Path(__file__).with_name("npc_group_fixture.txt")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {len(NAMES)} pairs to {output}")


if __name__ == "__main__":
    main()
